DROP TABLE IF EXISTS CART_ITEM CASCADE;
DROP TABLE IF EXISTS PRODUCT CASCADE;
DROP TABLE IF EXISTS SHIPPING_ADDRESS CASCADE;
DROP TABLE IF EXISTS USER_ORDER CASCADE;

CREATE TABLE PRODUCT (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    price INT NOT NULL,
    quantity INT NOT NULL,
    image_url VARCHAR(250) NOT NULL
);

CREATE TABLE CART_ITEM (
   id INT AUTO_INCREMENT PRIMARY KEY,
   session_id VARCHAR(250) NOT NULL,
   quantity INT NOT NULL,
   product_id INT references product(id)
);

CREATE TABLE SHIPPING_ADDRESS(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    city VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    house_number INT NOT NULL
);

CREATE TABLE USER_ORDER (
   id INT AUTO_INCREMENT PRIMARY KEY,
   status INT NOT NULL,
   address_id INT references SHIPPING_ADDRESS(id)
);
